### ISSUE TITLE
Pinentry error S ERROR curses.isatty 83918950

### ISSUE THREAD

**Issue by woolmonkey** [quexten/goldwarden#67] opened 2024-01-18 06:20 UTC
So I get the sudo prompt when trying to setup the pin. then I get the following error.
Pin updating failed: pinentry: unexpected response: "S ERROR curses.isatty 83918950 "

**Comment by woolmonkey** [comment] 2024-01-18 12:44
Ok a workaround I found is to remove pinentry then linked pinentry-gnome to pinentry.  That way I got the gnome popup for the entry.

**Comment by quexten** [comment] 2024-01-19 03:13
So the sudo prompt is a fallback for when there is no polkit policy in place, to still work with polkit by using the pkexec policy, which is in place in most systems. I think it might make sense to change this behaviour for the flatpak though, to by default only ask for the pin, and use biometrics (polkit) after setting up properly.

**Comment by quexten** [comment] 2024-01-19 03:13
>  Pin updating failed: pinentry: unexpected response: "S ERROR curses.isatty 83918950 "

This is something different though, apparently the fallback fails. What desktop environment / distribution are you on?

**Comment by quexten** [comment] 2024-01-19 08:19
Actually, I think this might be a duplicate of https://github.com/quexten/goldwarden/issues/56 and fixed in https://github.com/quexten/goldwarden/pull/60

**Comment by woolmonkey** [comment] 2024-01-20 14:50
I saw those but my display is :0.
I'm using gnome on Arch.

**Comment by mufeedali** [comment] 2024-01-20 15:12
> Actually, I think this might be a duplicate of https://github.com/quexten/goldwarden/issues/56 and fixed in https://github.com/quexten/goldwarden/pull/60

It should be

> I saw those but my display is :0.

Does restarting the systemd service work for you?

**Comment by 4e6963** [comment] 2024-01-21 01:33
I am using v0.2.10 on manjaro with gnome and receive the same error message when setting the pin. It seems like the last release didnt fix the issue.

**Comment by mufeedali** [comment] 2024-01-21 10:06
> I am using v0.2.10

Did you upgrade from the previous release? If so, did you run `goldwarden setup systemd` again?

**Comment by 4e6963** [comment] 2024-01-21 10:53
I installed goldwarden for the first time, today. So there was never an older version installed on my machine. I also verified that the changes in PR #60 are present in my systemd service file.

**Comment by quexten** [comment] 2024-01-21 11:07
> I am using v0.2.10 on manjaro with gnome and receive the same error message when setting the pin. It seems like the last release didnt fix the issue.
> 
> Installed pinentry is: pinentry-curses (pinentry) 1.2.1
> 
> EDIT: My current workaround is to configure pinentry-qt in `gpg-agent.conf`

I don't think pinentry curses can work in this context, since it is cli based. The pinentry is spawned in the daemon process which is spawned by systemd. The CLI that you call when logging in does not spawn a pinentry, but just talks to the daemon via a socket. We could add an alternative mode to pass the pin directly when calling the pin set command.

**Comment by quexten** [comment] 2024-01-21 11:08
> Ok a workaround I found is to remove pinentry then linked pinentry-gnome to pinentry. That way I got the gnome popup for the entry.

@woolmonkey Before you linked the gnome pinentry, which pinentry did you use? Also pinentry-curses?

**Comment by mufeedali** [comment] 2024-01-21 11:25
I think the real issue here is that pinentry in Arch is very... uncomplicated ig?

https://gitlab.archlinux.org/archlinux/packaging/packages/pinentry/-/blob/main/pinentry?ref_type=heads

**Comment by skydiablo** [comment] 2024-02-07 14:37
> I am using v0.2.10 on manjaro with gnome and receive the same error message when setting the pin. It seems like the last release didnt fix the issue.
> 
> Installed pinentry is: pinentry-curses (pinentry) 1.2.1
> 
> EDIT: My current workaround is to configure pinentry-qt in `gpg-agent.conf`

hm, there is only this file i had found: `/etc/pacman.d/gnupg/gpg-agent.conf` 

so how can i configure `pinentry-qt` in this file?

**Comment by quexten** [comment] 2024-02-17 13:59
Should be fixed in v0.2.12. If not please re-open.

**Closed by quexten** 2024-02-17 13:59 UTC
Labels: bug, duplicate, needs testing

**Comment by blackthorne7** [comment] 2024-05-01 21:46
I had the same "S ERROR curses.isatty 83918950" as off v0.2.16

reconfirming that using a graphical pinentry instead of curses/cli fixes the issue.

**Comment by quexten** [comment] 2024-05-01 22:09
@blackthorne7 on CLI or flatpak(gui)? The latter should fall back to a custom approval prompt.

**Comment by Adolar0042** [comment] 2024-05-13 06:58
facing the same error as of 0.3.2 - fresh install via AUR, running endeavourOS `6.8.9-arch1-2` with gnome `46.1` and pinentry `1.3.0`

**Comment by MmyGgithubAaccount** [comment] 2024-06-12 10:04
Just wanted to say that I was facing the same issue on the cli version on arch running plasma. Fixed by setting `pinentry-program pinentry-qt` in `~/.gnugpg/gpg-agent.conf` and restarting the service (`systemctl --user restart goldwarden.service`) as mentioned as above
