### ISSUE TITLE
Firefox is not detected for setup browserbiometrics unless the native-messaging-hosts folder already exists.

### ISSUE THREAD

**Issue by Anthony-Fiddes** [quexten/goldwarden#37] opened 2023-12-30 17:32 UTC
Here is an example to illustrate the issue:

```
~/.mozilla ··········································································································································· 18:19:59
❯ goldwarden setup browserbiometrics
Found chrome-like browser: /home/anthonyfiddes/.config/google-chrome/NativeMessagingHosts
Found chrome-like browser: /home/anthonyfiddes/.config/thorium/NativeMessagingHosts
Done.

~/.mozilla ··········································································································································· 18:20:16
❯ mkdir native-messaging-hosts

~/.mozilla ··········································································································································· 18:20:17
❯ goldwarden setup browserbiometrics
Found chrome-like browser: /home/anthonyfiddes/.config/google-chrome/NativeMessagingHosts
Found chrome-like browser: /home/anthonyfiddes/.config/thorium/NativeMessagingHosts
Found mozilla-like browser: /home/anthonyfiddes/.mozilla/native-messaging-hosts
Done.
```

Maybe we could add instructions to the wiki page about this, since I'm not sure if goldwarden is supposed to create the folder, or if the folder is already supposed to exist and for some reason does not. 

I personally use librewolf and cloned the repo to add `.librewolf` as a folder to search when I noticed this.

**Comment by Anthony-Fiddes** [comment] 2023-12-30 17:38
Right now I'm stuck here:

Brave:

![image](https://github.com/quexten/goldwarden/assets/11233666/9c7b3a68-7e63-453a-9548-a7980e731e5e)

Librewolf:

![image](https://github.com/quexten/goldwarden/assets/11233666/33e35587-0abb-41df-92eb-c81c4274c5f5)

**Comment by quexten** [comment] 2023-12-30 18:43
Thanks so much for the report. I'll update the wiki. For automatic setup, ideally a folder would be created. The issue is that the nativemessaginghosts folder is used to dynamically detect browsers. When the folder is not present, the best alternative would be to let the user manually select the browser's config directory, or hard-coding some paths. I'll think about this.

> I tried downloading the regular Bitwarden application and enabling fingerprint there. I wasn't sure that was the right thing to do but I wondered if it would create the needed folders (it did not) or do something else needed to make the fingerprint auth work:

The regular linux desktop app does not support biometrics. I do have PR open that adds support:
https://github.com/bitwarden/clients/pull/4586
but I'm unsure about Bitwarden's progress on reviewing that.

**Comment by quexten** [comment] 2023-12-30 18:45
For getting your extensions configured in Librewolf and Brave; I have not tested them, but since they are basically just Firefox and Chromium, this should just be a matter of getting the manifest into the correct place. 

Just to make sure, are the browsers installed as flatpak? (In that case the sandboxing prevents IPC from working)

**Comment by Anthony-Fiddes** [comment] 2023-12-30 19:02
Thanks for the advice! I'll keep messing around with it and let you know how it goes. Maybe I'll try getting it working in Chromium or Chrome before anything else.

Also they are natively installed, so that part should be fine:

![image](https://github.com/quexten/goldwarden/assets/11233666/bc579793-9eb4-45e9-8055-2e53acc9bcea)

**Comment by quexten** [comment] 2023-12-30 19:07
Can you try running:
`rsync -avzP  /home/anthonyfiddes/.mozilla/native-messaging-hosts/  /home/anthonyfiddes/.librewolf/native-messaging-hosts/`

And `rsync -avzP /home/anthonyfiddes/.config/google-chrome/NativeMessagingHosts/ /home/anthonyfiddes/.config/BraveSoftware/NativeMessagingHosts/`

**Comment by quexten** [comment] 2023-12-30 20:07
Just released https://github.com/quexten/goldwarden/releases/tag/v0.2.7, which should automatically create the native-messaging-host paths for many browsers, including librewolf and brave. You can try updating, and re-running the setup.

**Comment by Anthony-Fiddes** [comment] 2023-12-30 23:26
Hey @quexten, I tried out the new release and it works well, creating the folders where they don't exist. The only thing I get now is this message from Bitwarden to confirm in my desktop application:

![image](https://github.com/quexten/goldwarden/assets/11233666/41eee23d-e32c-489b-9de4-1db30fcb2d5e)

Which is definitely better than before. I tried purging my vault and logging in again and calling the setup for systemd again.

When I check journalctl, this is the output:

```
Dec 31 00:19:12 Fiddes-Thinkpad goldwarden[6437]: [INF] [00:19] [Goldwarden > Websocket] >>> Connected to websocket server...
Dec 31 00:19:26 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:19] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:19:29 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:19] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:19:29 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:19] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:19:30 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:19] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:19:32 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:19] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:19:33 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:19] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:19:34 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:19] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:19:42 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:19] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:19:46 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:19] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:21:02 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:21] [Goldwarden > Websocket] >>> Update requested for cipher 2a2c2573-e34b-4019-b2cd-aa9c0004d3f1
Dec 31 00:21:08 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:21] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:21:26 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:21] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:21:29 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:21] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:21:29 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:21] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:21:30 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:21] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:21:32 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:21] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:21:33 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:21] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:21:34 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:21] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:21:42 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:21] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 31 00:21:46 Fiddes-Thinkpad goldwarden[6437]: [WRN] [00:21] [Goldwarden > Websocket] >>> Invalid message received, length too short
lines 369-409/409 (END)
```

And I'm not using my local build:

![image](https://github.com/quexten/goldwarden/assets/11233666/1945b6b4-0007-4507-8948-764c5430d26b)

With this part I may be missing something simple to tie it all together. I get the same message when I try in Brave as well.

**Comment by spyfly** [comment] 2024-01-05 12:50
> Hey @quexten, I tried out the new release and it works well, creating the folders where they don't exist. The only thing I get now is this message from Bitwarden to confirm in my desktop application:

Stuck at the same message, "Awaiting confirmation from Desktop", both in Firefox and Chrome.

**Comment by quexten** [comment] 2024-01-05 13:16
Ah, sorry forgot to follow up on the issue until now. Can either of you compile with `go build -tags debuglogging .`, and then post systemd service logs, and `/tmp/DELETE_ME.log`. **DO BE CAREFUL TO REMOVE SECERTS**, usually these should not be logged, but just in case they are, manually check.

**Comment by Anthony-Fiddes** [comment] 2024-01-07 17:30
Hey @quexten,

I just emailed you (from your website on your profile) a secure Bitwarden note with the text from the log after pulling the latest main (I redacted some stuff on the lines marked SENSITIVE, but I sent a note expiring in a month just to be safe). 

I built goldwarden as you instructed, copying to /usr/bin/goldwarden and restarting the systemd service. All I did was attempt to enable biometrics in the extension like before to generate the log.

**Comment by Anthony-Fiddes** [comment] 2024-01-07 17:31
The journalctl logs are still just full of `[WRN] [18:22] [Goldwarden > Websocket] >>> Invalid message received, length too short`

**Comment by quexten** [comment] 2024-01-07 21:37
Thanks a lot for the log!

> The journalctl logs are still just full of `[WRN] [18:22] [Goldwarden > Websocket] >>> Invalid message received, length too short`

This is unrelated, but due to keepalives the official server implementation sends, which I have not implemented proper filtering for yet.

> [ERROR] 2024-01-07 18:12:51 Unable to send message to agent: dial unix: missing address

This seems to be the issue, for some reason goldwarden - when invoked by your browser - seems not to have a socket path, and thus can't connect to the daemon. The rest of the handshake seems fine. Not entirely sure yet why this is happening, but it's a good clue!

**Comment by quexten** [comment] 2024-01-07 22:02
I think I found the issue (01aca3582f475f314031013bbb598bc56a582ac9), should be fixed on the latest master version.

**Comment by Anthony-Fiddes** [comment] 2024-01-08 11:10
I tried it out and it worked! The only problem I'm finding now is that my vault keeps getting corrupted like in this issue: https://github.com/quexten/goldwarden/issues/38. The vault purge and log in step fixed it, but I had to do it 2 or 3 times.

**Comment by quexten** [comment] 2024-01-08 17:29
Thanks, closing this now.

**Closed by quexten** 2024-01-08 17:29 UTC
Labels: bug
