### ISSUE TITLE
Submit the Login form on pressing Enter in the Email field

### ISSUE THREAD

**Issue by MurzNN** [quexten/goldwarden#72] opened 2024-01-20 09:06 UTC
Please make the Login form submittable by pressing Enter in the Email field.

Now I have to press "Tab" triple times to make the "Login" button active, and only then the "Enter" starts work well.

Also, I think it's better to make the "Email" field active by default, instead of the first "API Url" field, because in most cases only the Email should be entered there by user.

**Comment by quexten** [comment] 2024-01-20 12:29
Changed the order in ce17426063f0cf04b9e28297745186f77ca40c65

![image](https://github.com/quexten/goldwarden/assets/11866552/6c725e8b-686f-4dce-b852-ee944d2f0fb9)

**Comment by quexten** [comment] 2024-05-03 23:25
Seems to be duplicate of #188. Same as that issue, this is fixed on the main branch now.

**Closed** 2024-05-04 01:49 UTC
Labels: duplicate, enhancement, needs testing
